# Generated by Django 6.0.4 on 2026-04-28 16:31

import django.db.models.deletion
from django.db import migrations, models


def assign_clients_to_default_organization(apps, schema_editor):
    Organization = apps.get_model('users', 'Organization')
    Client = apps.get_model('clients', 'Client')

    default_organization, _ = Organization.objects.get_or_create(
        slug='default-organization',
        defaults={'name': 'Default Organization'},
    )

    Client.objects.filter(organization__isnull=True).update(organization=default_organization)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0003_organization_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='users.organization'),
        ),
        migrations.RunPython(
            assign_clients_to_default_organization,
            migrations.RunPython.noop,
        ),
    ]
