# Generated by Django 6.0.4 on 2026-04-30 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_organization'),
        ('users', '0003_organization_user_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['organization', 'is_active'], name='client_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['organization', 'full_name'], name='client_org_name_idx'),
        ),
    ]
