# Generated by Django 6.0.4 on 2026-05-06 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_client_org_active_idx_and_more'),
        ('users', '0004_user_user_org_role_idx_user_user_org_active_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('organization', 'phone'), name='unique_client_phone_per_org'),
        ),
    ]
