services:
  db:
    image: postgres:18
    container_name: orvanta_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - orvanta_postgres_data:/var/lib/postgresql

  web:
    build: .
    container_name: orvanta_web
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  orvanta_postgres_data: