# Generated by Django 6.0.4 on 2026-04-28 16:10

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_users_to_default_organization(apps, schema_editor):
    Organization = apps.get_model('users', 'Organization')
    User = apps.get_model('users', 'User')

    default_organization, _ = Organization.objects.get_or_create(
        slug='default-organization',
        defaults={'name': 'Default Organization'},
    )

    User.objects.filter(organization__isnull=True).update(organization=default_organization)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Організація',
                'verbose_name_plural': 'Організації',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.organization'),
        ),
        migrations.RunPython(
            assign_existing_users_to_default_organization,
            migrations.RunPython.noop,
        ),
    ]
