# Generated by Django 6.0.4 on 2026-04-22 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('planned', 'Заплановано'), ('confirmed', 'Підтверджено'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='planned', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_appointments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services_catalog.service')),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
                'ordering': ['-appointment_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('planned', 'Заплановано'), ('confirmed', 'Підтверджено'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], max_length=20)),
                ('new_status', models.CharField(choices=[('planned', 'Заплановано'), ('confirmed', 'Підтверджено'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='appointments.appointment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_appointment_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Історія статусу запису',
                'verbose_name_plural': 'Історія статусів записів',
                'ordering': ['-changed_at'],
            },
        ),
    ]
