# Generated by Django 6.0.4 on 2026-04-28 17:31

import django.db.models.deletion
from django.db import migrations, models


def assign_appointments_to_organization(apps, schema_editor):
    Organization = apps.get_model('users', 'Organization')
    Appointment = apps.get_model('appointments', 'Appointment')
    AppointmentStatusHistory = apps.get_model('appointments', 'AppointmentStatusHistory')

    default_organization, _ = Organization.objects.get_or_create(
        slug='default-organization',
        defaults={'name': 'Default Organization'},
    )

    appointments = Appointment.objects.select_related(
        'client',
        'service',
        'created_by',
    ).filter(organization__isnull=True)

    for appointment in appointments:
        if appointment.client_id and appointment.client and appointment.client.organization_id:
            appointment.organization_id = appointment.client.organization_id
        elif appointment.service_id and appointment.service and appointment.service.organization_id:
            appointment.organization_id = appointment.service.organization_id
        elif appointment.created_by_id and appointment.created_by and appointment.created_by.organization_id:
            appointment.organization_id = appointment.created_by.organization_id
        else:
            appointment.organization = default_organization
        appointment.save(update_fields=['organization'])

    history_items = AppointmentStatusHistory.objects.select_related(
        'appointment',
        'changed_by',
    ).filter(organization__isnull=True)

    for history_item in history_items:
        if history_item.appointment_id and history_item.appointment and history_item.appointment.organization_id:
            history_item.organization_id = history_item.appointment.organization_id
        elif history_item.changed_by_id and history_item.changed_by and history_item.changed_by.organization_id:
            history_item.organization_id = history_item.changed_by.organization_id
        else:
            history_item.organization = default_organization
        history_item.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clients', '0002_client_organization'),
        ('services_catalog', '0002_service_organization_servicecategory_organization'),
        ('users', '0003_organization_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='users.organization'),
        ),
        migrations.AddField(
            model_name='appointmentstatushistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_status_history', to='users.organization'),
        ),
        migrations.RunPython(
            assign_appointments_to_organization,
            migrations.RunPython.noop,
        ),
    ]
