# Generated by Django 6.0.4 on 2026-04-30 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_organization_and_more'),
        ('clients', '0002_client_organization'),
        ('services_catalog', '0002_service_organization_servicecategory_organization'),
        ('users', '0003_organization_user_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'appointment_date', 'start_time'], name='appt_org_date_start_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'status'], name='appt_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'employee', 'appointment_date', 'start_time', 'end_time'], name='appt_org_emp_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'service'], name='appt_org_service_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentstatushistory',
            index=models.Index(fields=['organization', '-changed_at'], name='appt_hist_org_changed_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentstatushistory',
            index=models.Index(fields=['organization', 'appointment', '-changed_at'], name='appt_hist_org_appt_idx'),
        ),
    ]
