# Generated by Django 6.0.4 on 2026-04-30 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_appt_org_date_start_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Може відрізнятися від базової вартості послуги.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фактична вартість'),
        ),
    ]
