# Generated by Django 6.0.4 on 2026-04-28 16:31

import django.db.models.deletion
from django.db import migrations, models


def assign_services_to_default_organization(apps, schema_editor):
    Organization = apps.get_model('users', 'Organization')
    ServiceCategory = apps.get_model('services_catalog', 'ServiceCategory')
    Service = apps.get_model('services_catalog', 'Service')

    default_organization, _ = Organization.objects.get_or_create(
        slug='default-organization',
        defaults={'name': 'Default Organization'},
    )

    ServiceCategory.objects.filter(organization__isnull=True).update(organization=default_organization)

    services = Service.objects.select_related('category').filter(organization__isnull=True)
    for service in services:
        if service.category_id and service.category and service.category.organization_id:
            service.organization_id = service.category.organization_id
        else:
            service.organization = default_organization
        service.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('services_catalog', '0001_initial'),
        ('users', '0003_organization_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='users.organization'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_categories', to='users.organization'),
        ),
        migrations.RunPython(
            assign_services_to_default_organization,
            migrations.RunPython.noop,
        ),
    ]
