# Generated by Django 6.0.4 on 2026-04-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_catalog', '0002_service_organization_servicecategory_organization'),
        ('users', '0003_organization_user_organization'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['organization', 'is_active'], name='svc_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['organization', 'category'], name='svc_org_category_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['organization', 'name'], name='svc_org_name_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['organization', 'name'], name='svc_cat_org_name_idx'),
        ),
    ]
