# Generated by Django 6.0.4 on 2026-05-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_catalog', '0003_service_svc_org_active_idx_and_more'),
        ('users', '0004_user_user_org_role_idx_user_user_org_active_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='service',
            name='unique_service_per_category',
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('organization', 'category', 'name'), name='unique_service_per_org_category'),
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_service_category_per_org'),
        ),
    ]
