# Generated by Django 6.0.4 on 2026-04-22 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Вхід'), ('logout', 'Вихід'), ('create', 'Створення'), ('update', 'Оновлення'), ('delete', 'Видалення'), ('change_status', 'Зміна статусу'), ('assign_role', 'Призначення ролі')], max_length=30)),
                ('entity_type', models.CharField(choices=[('user', 'Користувач'), ('client', 'Клієнт'), ('service', 'Послуга'), ('appointment', 'Запис'), ('auth', 'Автентифікація')], max_length=30)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запис аудиту',
                'verbose_name_plural': 'Журнал аудиту',
                'ordering': ['-created_at'],
            },
        ),
    ]
