# Generated by Django 6.0.4 on 2026-04-28 17:31

import django.db.models.deletion
from django.db import migrations, models


def assign_audit_logs_to_organization(apps, schema_editor):
    Organization = apps.get_model('users', 'Organization')
    AuditLog = apps.get_model('audit', 'AuditLog')

    default_organization, _ = Organization.objects.get_or_create(
        slug='default-organization',
        defaults={'name': 'Default Organization'},
    )

    logs = AuditLog.objects.select_related('user').filter(organization__isnull=True)

    for log in logs:
        if log.user_id and log.user and log.user.organization_id:
            log.organization_id = log.user.organization_id
        else:
            log.organization = default_organization
        log.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('users', '0003_organization_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.organization'),
        ),
        migrations.RunPython(
            assign_audit_logs_to_organization,
            migrations.RunPython.noop,
        ),
    ]
